# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftSampleBasic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

    # Reactive Extensions
  pod 'RxCocoa'
  pod 'RxSwift'
  pod 'Action'
  pod 'RxWebKit'
  pod 'APIKit'

end
